services:
  - type: pserv
    name: karaoke-mysql-db
    env: docker
    repo: https://github.com/render-examples/mysql
    dockerfile: Dockerfile
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root_secure_password_123
      - key: MYSQL_DATABASE
        value: karaoke_booking
      - key: MYSQL_USER
        value: dung_admin
      - key: MYSQL_PASSWORD
        value: dung_password_123

  - type: web
    name: karaoke-backend-api
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://karaoke-mysql-db:3306/karaoke_booking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: dung_admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dung_password_123
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: MY_JWT_SECRET
        value: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==