# spring.application.name=karaokebooking

# #config database
# ###
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=jdbc:mysql://localhost:3306/karaoke_booking
# spring.datasource.username=root
# spring.datasource.password=123456789
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.show-sql: true

# dungmount.jwt.base64-secret=qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
# dungmount.jwt.access-token-validity-in-seconds=8640000
# dungmount.jwt.refresh-token-validity-in-seconds=8640000



spring.application.name=karaokebooking

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}

spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

server.port=${PORT:8080}

dungmount.jwt.base64-secret=${JWT_SECRET}
dungmount.jwt.access-token-validity-in-seconds=8640000
dungmount.jwt.refresh-token-validity-in-seconds=8640000