# spring.application.name=karaokebooking

# #config database
# ###
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=jdbc:mysql://localhost:3306/karaoke_booking
# spring.datasource.username=root
# spring.datasource.password=123456789
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.show-sql: true

# dungmount.jwt.base64-secret=qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
# dungmount.jwt.access-token-validity-in-seconds=8640000
# dungmount.jwt.refresh-token-validity-in-seconds=8640000



# spring.application.name=karaokebooking

# # Cấu hình Database thông minh: Ưu tiên lấy từ biến môi trường, nếu không có thì dùng localhost
# server.port=${PORT:8080}
# spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
# # spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}

# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/karaoke_booking}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456789}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.show-sql=true

# # Giữ nguyên cấu hình JWT của bạn
# dungmount.jwt.base64-secret=${MY_JWT_SECRET:qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==}
# dungmount.jwt.access-token-validity-in-seconds=8640000
# dungmount.jwt.refresh-token-validity-in-seconds=8640000

# spring.sql.init.mode=always


# spring.application.name=karaokebooking
# server.port=${PORT:8080}

# # 1. CẤU HÌNH DATABASE POSTGRESQL
# # URL mặc định khi chạy dưới local sẽ dùng cổng 5432 và database đặt tên là karaoke_booking
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/karaoke_booking}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
# spring.datasource.driver-class-name=org.postgresql.Driver

# # 2. CẤU HÌNH HIBERNATE / JPA CHO POSTGRESQL
# spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
# spring.jpa.show-sql=true
# # Chỉ định Dialect cụ thể cho PostgreSQL để Hibernate sinh câu lệnh SQL chuẩn xác
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # Giữ nguyên cấu hình JWT của bạn
# dungmount.jwt.base64-secret=${MY_JWT_SECRET:qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==}
# dungmount.jwt.access-token-validity-in-seconds=8640000
# dungmount.jwt.refresh-token-validity-in-seconds=8640000



#=========SUPABASE========================

spring.application.name=karaokebooking

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Sử dụng biến môi trường để bảo mật, nếu không có biến trên Render sẽ tự lấy giá trị mặc định sau dấu hai chấm
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.slnqrbxqpmoutlkqohnf}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Taidung2026Singeasy}

spring.datasource.driver-class-name=org.postgresql.Driver


dungmount.jwt.base64-secret=${MY_JWT_SECRET:qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==}
dungmount.jwt.access-token-validity-in-seconds=8640000
dungmount.jwt.refresh-token-validity-in-seconds=8640000